### ISSUE TITLE
请问该项目开发完成了吗?想拉取下来学习一下?可以吗

### ISSUE THREAD

**Issue by hexonal** [jxnu-liguobin/seckillPro#1]

**Comment by jxnu-liguobin** [comment]
可以拉下学习，目前剩下 redis库存初始化 用户限流 websocket主动推送结果 、压力测试、集成测试  这些没完成

**Comment by hexonal** [comment]
能提供一份sbt的国内仓库配置文件吗?看了网上很多教程,再加载play框架项目的时候,发现下载依赖奇慢无比

**Comment by jxnu-liguobin** [comment]
`vi ~/.sbt/repositories

[repositories]
local
aliyun: http://maven.aliyun.com/nexus/content/groups/public/
typesafe: http://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext], bootOnly
sonatype-oss-releases
maven-central
sonatype-oss-snapshots`

这是我的。我是Mac，windows路径改变下。使用SBT1.2x

**Comment by hexonal** [comment]
好的!非常感谢
